[tool.pylint.main]
ignore = [".venv"]
recursive = true

[tool.pylint.messages_control]
disable = [
    "line-too-long", # disable because we use autopep8
]

[tool.autopep8]
max_line_length = 120
recursive = true
exit_code = true
